apiVersion: v1
kind: ConfigMap
metadata:
  name: teachme-backend-config
  namespace: teachme
data:
  NODE_ENV: "production"
  PORT: "3000"
  KEYCLOAK_URL: "http://teachme-keycloak-service:8080"
  KEYCLOAK_REALM: "teachme"
