services:
  backend:
    build:
      context: ./be
      dockerfile: dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - assets:/app/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: dockerfile
    image: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - app-network

  blog:
    container_name: learning_blog
    build:
      context: ./blog
      dockerfile: dockerfile
    ports: 
      - '8081:80'
    networks:
      - app-network

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # if the certificate has expired, uncomment the below line and run "docker compose up -d"
      - web-root:/var/www/html
    depends_on:
      - frontend
      - blog
      - keycloak
    networks:
      - app-network

  keycloak_db:
    image: postgres
    container_name: keycloak_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file: "./keycloak/.db.env"
    networks:
      - app-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: dockerfile
    container_name: keycloak
    env_file: "./keycloak/.env"
    ports:
      - '8443:8443'
      - '9000:9000'
    volumes:
      - ./conf:/opt/keycloak/conf
    depends_on:
      - keycloak_db
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - frontend
      - keycloak
    command: certonly -v --webroot --webroot-path=/var/www/html --email jakob.lingel@hotmail.de --agree-tos --no-eff-email --force-renewal -d teachly.store -d www.teachly.store -d blog.teachly.store -d www.blog.teachly.store -d auth.teachly.store -d www.auth.teachly.store

volumes:
  certbot-etc:
  certbot-var:
  assets:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
