services:
  backend:
    build:
      context: ./be
      dockerfile: dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - assets:/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: dockerfile.develop
    image: frontend_local
    container_name: frontend_local
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      #volumes:
      # - web-root:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: dockerfile
    image: keycloak_local
    container_name: my_keycloak_local
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=change_me
    ports:
      - '8443:8443'
      - '9000:9000'
   command: 
      - "start"
      - "--optimized"
      - "--hostname=localhost"

volumes:
  assets:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
