services:
  backend:
    build:
      context: ./be
      dockerfile: dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - assets:/app/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: dockerfile
    image: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - app-network

  keycloak_db:
    image: postgres
    container_name: keycloak_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file: "./keycloak/.db.env"
    networks:
      - app-network
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./keycloak
      dockerfile: dockerfile
    container_name: keycloak
    env_file: "./keycloak/.env"
    ports:
      - '8082:8080'
      - '9000:9000'
    volumes:
      - ./conf:/opt/keycloak/conf
    depends_on:
      - keycloak_db
    networks:
      - app-network

volumes:
  assets:
  web-root:
    driver: local
  keycloak_db_data:

networks:
  app-network:
    external: true
