services:
  backend:
    build:
      context: ./be
      dockerfile: dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - assets:/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: dockerfile.develop
    image: frontend_local
    container_name: frontend_local
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      #volumes:
      # - web-root:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  assets:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
