@startuml

component Keycloak
component Frontend
component Backend {
  storage assets
}
database postgres

Frontend -do0)-- Backend
Frontend -ri0)-- Keycloak
Backend -le0)- Keycloak
Backend --> postgres

@enduml
