FROM node:20-alpine AS base

WORKDIR /app

COPY package.json .

RUN npm install --omit=dev
RUN npm install typescript
RUN npm install vite

COPY . .

FROM base AS build
RUN npm run build

FROM nginx:latest
COPY --from=build /app/dist /var/www/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
