FROM node:20-alpine AS base

WORKDIR /app

COPY package.json .

RUN npm install --omit=dev
RUN npm install typescript
RUN npm install vite

COPY . .

FROM base AS build
RUN npm run build

hello there
