FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS base

WORKDIR /app

COPY package.json .

RUN npm install --omit=dev
RUN npm install typescript
RUN npm install vite

COPY . .

FROM base AS build
RUN npm run build
