FROM node:latest

COPY . /app

WORKDIR /app

RUN npm install --omit=dev
RUN npm install typescript
RUN npm install vite

RUN npm run build

FROM nginx:latest

COPY --from=0 /app/dist /usr/share/nginx/html
COPY --from=0 /app/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
