services:
  backend:
    build:
      context: ./be
      dockerfile: dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - assets:/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: dockerfile.develop
    image: frontend_local
    container_name: frontend_local
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      #volumes:
      # - web-root:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: dockerfile
    image: keycloak_local
    container_name: my_keycloak_local
    env_file: "./keycloak/.env"
    ports:
      - '8443:8443'
      - '9000:9000'
    command: 
      - "start"
      - "--optimized"
      - "--hostname=localhost"

  keycloak_db:
    image: postgres
    container_name: keycloak_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file: "./keycloak/.db.env"

volumes:
  assets:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
