FROM node:22-bullseye AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
  ghostscript \
  graphicsmagick \
  poppler-utils

WORKDIR /app

COPY package.json .

RUN npm install --omit=dev
RUN npm install @nestjs/cli
COPY . .

FROM base AS build 
RUN npm run build

FROM build AS production

COPY --from=build /app/dist .
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
CMD ["npm", "run", "start:prod"]

EXPOSE 3000
