FROM node:latest as base

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install --omit=dev
RUN npm install @nestjs/cli
COPY . .

FROM base as build 
RUN npm run build

FROM build as production
COPY --from=build /app/dist .
CMD ["npm", "run", "start:prod"]

EXPOSE 3000
