name: Update reverse-proxy nginx config via SSH

on: 
  push:
    branches:
      - main
      - master
    paths: 
      - 'deploy/reverse-proxy/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd /root/teachme/deploy/reverse-proxy
            docker compose up -d certbot || exit 1
            TIMEOUT=30
            START_TIME=$SECONDS
            while true; do
              if docker logs certbot 2>&1 | grep -q "Successfully received certificate"; then
                echo "Certbot has finished successfully!"
                break
              elif docker logs certbot 2>&1 | grep -q "error" || (( $SECONDS - START_TIME > $TIMEOUT )); then
                echo "Certbot failed or timed out!"
                docker compose logs certbot # Print Certbot logs for debugging
                exit 1
              fi
              echo "Waiting for certbot to finish..."
              sleep 3
            done
            echo "Certbot has finished successfully!"
            docker compose stop reverse-proxy || exit 1
            docker compose up -d reverse-proxy || exit 1
