name: Update reverse-proxy nginx config via SSH

on: 
  push:
    branches:
      - main
      - master
    paths: 
      - 'deploy/reverse-proxy/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd /root/teachme/deploy/reverse-proxy
            docker compose up -d certbot || exit 1
            docker compose stop reverse-proxy || exit 1
            docker compose up -d reverse-proxy || exit 1
