on: 
  push:
    branches:
      - main
      - master
jobs: 
  sftp_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SFTP_Deploy
      # You may pin to the exact commit or the version.
      # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        # username
        username: root
        # your sftp server
        server: 164.92.171.183
        # you can copy private_key from your *.pem file, keep format
        local_path: .
        # files will copy to under remote_path
        remote_path: /root/teachme
        # connection via sftp protocol only
        # SSH passsword，If a password is set, the secret key pair is ignored
        password: ${{ secrets.SERVER_PASSWORD }}
  
