on: 
  push:
    branches:
      - main
      - master
jobs: 
  ssh_deploy:
    runs-on: ubuntu-latest
    steps:  
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.SERVER_ADDRESS }}
        REMOTE_USER: ${{ secrets.USER_NAME }}
        REMOTE_PORT: 22
        TARGET: /root/teachme
        EXCLUDE: /.git/
        SCRIPT_AFTER: |
          cd /root/teachme
          docker compose build || exit 1
          docker compose down || exit 1
          docker compose up -d || exit 1
        SCRIPT_AFTER_REQUIRED: true
